### PR TITLE
Update service-parent to version 2

### PR DESCRIPTION
**Pull request by ligangty**

### CODE REVIEW

**Comment by ruhan1** [comment]
I tried the 2 and hit 'package io.smallrye.reactive.messaging.connectors does not exist' and compiling failed. I am wondering if sth change caused this.

**Comment by ligangty** [comment]
@ruhan1 weird. I did not meet this problem. Can you help clean the .m2 caches of that package and try again?

**Comment by ligangty** [comment]
@ruhan1 I'll merge this as it is just a pom change and passed the CI. If you still have issues please create a issue to track here.

**Comment by ruhan1** [comment]
Ok, I will try cleaning my env.

**Pull request merged**
